include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "build/**"
    - "assets/**"

  errors:
    avoid_print: warning
    todo: info
    prefer_const_constructors: warning
    prefer_const_literals_to_create_immutables: warning
    avoid_dynamic_calls: warning
    public_member_api_docs: ignore
    lines_longer_than_80_chars: ignore
    cascade_invocations: ignore
    use_setters_to_change_properties: ignore

linter:
  rules:
    # === CRITICAL RULES TO KEEP ===
    - avoid_returning_null_for_void
    - prefer_void_to_null
    - avoid_init_to_null
    - unawaited_futures
    - cancel_subscriptions
    - close_sinks
    - avoid_slow_async_io
    - no_logic_in_create_state
    - use_build_context_synchronously
    - prefer_final_locals
    - unnecessary_null_checks
    - avoid_unnecessary_containers
    - sized_box_for_whitespace

    # === RULES TO DISABLE ===
    - public_member_api_docs: false
    - prefer_single_quotes: false
    - lines_longer_than_80_chars: false
